add or35
WarrenKnocker/coding-bat pull request #20
Opened 2023-07-31 08:50 UTC by WarrenKnocker

2023-08-02 10:49 UTC, JustinGuedes requested changes

2023-08-02 10:49 UTC, JustinGuedes commented on WarmUp1/or35/src/index.ts
> +export function or35(NumParameter: number): boolean {
Name of the parameter is not following naming convention

2023-08-02 10:49 UTC, JustinGuedes commented on WarmUp1/or35/src/index.ts
> +  if (NumParameter % 3 == 0 || NumParameter % 5 == 0) {
Simplify the function please

2023-08-16 11:40 UTC, WarrenKnocker commented
Request to merge, updated function parameter naming & simplified function.

2024-04-16 05:43 UTC, merged