add front22
WarrenKnocker/coding-bat pull request #21
Opened 2023-07-31 11:18 UTC by WarrenKnocker

2023-08-02 10:51 UTC, JustinGuedes requested changes

2023-08-02 10:51 UTC, JustinGuedes commented on WarmUp1/Front22/src/index.ts
> +  let TempChar = strParameter.slice(0, 2);
Name is incorrect, and please make sure you use `const` instead of `let` by default

2023-08-02 10:51 UTC, JustinGuedes commented on WarmUp1/Front22/test/index.test.ts
> +describe("Front22", () => {
Please add a test with a string of one character

2023-08-16 11:32 UTC, WarrenKnocker commented
Request for merge, Naming and test updated

2024-04-16 05:44 UTC, merged