add sleepIn
WarrenKnocker/coding-bat pull request #8
Opened 2023-07-29 09:11 UTC by WarrenKnocker

2023-08-02 10:22 UTC, JustinGuedes requested changes

2023-08-02 10:22 UTC, JustinGuedes commented on WarmUp1/sleepIn/src/index.ts
> +else if (weekday == false && vacation == false ) {
What's the difference between the above condition?

2023-08-02 10:22 UTC, JustinGuedes commented on WarmUp1/sleepIn/src/index.ts
> +export function sleepIn(weekday: boolean, vacation: boolean): boolean {
Please format the function

2023-08-02 10:22 UTC, JustinGuedes commented on WarmUp1/sleepIn/src/index.ts
> +export function sleepIn(weekday: boolean, vacation: boolean): boolean {
Also please simplify the function

2023-08-16 12:20 UTC, WarrenKnocker commented
Request to merge. Simplified function

2024-04-16 05:44 UTC, merged